---
# From https://confluence.internal.salesforce.com/display/public/ZEN/Pipeline+Stages+In+Depth#PipelineStagesInDepth-Global.strata.ymlKeys
pipeline_template: utest-only/Jenkinsfile-1
email_reply_to: sfcdupstream@salesforce.com
docker_test_images:
  - dva/sfcd/spinnaker-build:latest
# Convince strata to stop using snyk's default (and specific to maven) args
snyk_build_args: "''"
# Prune the dependency tree since gate is a large project
# https://support.snyk.io/hc/en-us/articles/360002061438-CLI-returns-the-error-Failed-to-get-Vulns-
# Without pruning synk does not successfully run
snyk_cmd_args: "--all-projects --prune-repeated-subdependencies"
# gradle options match the upstream PR builds here:
# https://git.soma.salesforce.com/spinnaker/gate/blob/456acdadf26ebd84c0ca0e4d0d9808103a39d28c/.github/workflows/pr.yml#L6
unit_tests_command: gradleenv auto && GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx6g -Xms6g" ./gradlew build

production_branch:
  - release-1.21.x-sfcd
  - release-1.23.x-sfcd
